/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myapp_MainActivity */

#ifndef _Included_com_example_myapp_MainActivity
#define _Included_com_example_myapp_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_myapp_MainActivity
 * Method:    getHelloString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_myapp_MainActivity_getHelloString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
